from typing import TYPE_CHECKING, Protocol, Sequence

from shapely.geometry import Polygon

if TYPE_CHECKING:
    from prvosm.models.changeset import Changeset
    from prvosm.models.node import Node
    from prvosm.models.note import Note
    from prvosm.models.relation import FullRelation, Relation
    from prvosm.models.user import User
    from prvosm.models.way import FullWay, Way


class OSMClient(Protocol):
    def fetch_changeset(self, id: int) -> Changeset: ...
    def fetch_changeset_changes(self, id: int) -> None: ...
    def fetch_changeset_comments(self) -> None: ...

    # Node related functions
    def fetch_node(self, id: int) -> Node: ...
    def fetch_nodes(self, ids: Sequence[str | int]) -> list[Node]: ...
    def fetch_node_history(self, id: int) -> list[Node]: ...
    def fetch_node_version(self, id: int, version: int) -> Node: ...
    def fetch_ways_for_node(self, id: int) -> list[Way]: ...
    def fetch_relations_for_node(self, id: int) -> list[Relation]: ...

    # Notes related functions
    def fetch_note(self, id: int) -> Note: ...
    def fetch_notes(
        self, bbox: Polygon, limit: int | None = None, closed: int | None = None
    ) -> list[Note]: ...

    # Relation related functions
    def fetch_relation(self, id: int) -> Relation: ...
    def fetch_relations(self, ids: Sequence[str | int]) -> list[Relation]: ...
    def fetch_relation_history(self, id: int) -> list[Relation]: ...
    def fetch_relation_version(self, id: int, version: int) -> Relation: ...
    def fetch_relations_for_relation(self, id: int) -> list[Relation]: ...
    def fetch_full_relation(self, id: int) -> FullRelation: ...

    # User related functions
    def fetch_user(self, id: int) -> User: ...

    # Way related functions
    def fetch_way(self, id: int) -> Way: ...
    def fetch_ways(self, ids: Sequence[str | int]) -> list[Way]: ...
    def fetch_way_history(self, id: int) -> list[Way]: ...
    def fetch_way_version(self, id: int, version: int) -> Way: ...
    def fetch_relations_for_way(self, id: int) -> list[Relation]: ...
    def fetch_full_way(self, id: int) -> FullWay: ...
